package playgroundLoad;

import java.util.HashSet;


public class Nomi {
	
	private Nome[] people = {
			new Nome("AARON", "ASCENZI", "PROVINCIALE GIROLA 7"),
			new Nome("ABE", "MAZZANTE", "VIA ANDREA DA BOLOGNA"),
			new Nome("ABRAHAM", "MARCATILI", "VIA S.LUCIA 16"),
			new Nome("ABSALOM", "SANTARELLI", "MORANDI 47"),
			new Nome("ACE", "SARACONI", "VIA VALMIR 137"),
			new Nome("ADAM", "MARIOTTI", "G. DI VITTORIO 20"),
			new Nome("ADOLPH", "PETTINARI", "VIA S:BIAGIO"),
			new Nome("ADRIAN", "MARZETTI", "VIA ALFIERI 4"),
			new Nome("AL", "PACETTI", "VIA ALFIERI 16"),
			new Nome("ALAN", "VALLORANI", "VIA LORENZO LOTTO 9"),
			new Nome("BALDRIC", "MEDORI", "VIA S TOMMASO"),
			new Nome("BALDWIN", "CIUCANI", "VIA DELLA FRATELLANZA 71"),
			new Nome("BAPTIST", "PIERBATTISTA", "VIA SAN SISTO 16"),
			new Nome("BARCLAY", "CIMICA", "VIA SOLFERINO 4"),
			new Nome("BARNABAS", "FUNARI", "VIA FALERIENSE OVEST 39"),
			new Nome("BARNABY", "SCOCCIA", "VIA COLLE S.SALVATORE 21"),
			new Nome("BARNEY", "MARIANI", "VIA SOCCORSO"),
			new Nome("BARRET", "ILARI", "VIA DELLE ROSE 2"),
			new Nome("BARRETT", "DI VINCENZO", "VIA MICHELANGELO"),
			new Nome("BARRIE", "GIORGETTI", "VIA FORONE 2"),
			new Nome("CADE", "ARBUSTI", "VIA MAZZINI 86"),
			new Nome("CADEN", "ARMELLINI", "VIA LEOPARDI 26"),
			new Nome("CAESAR", "ASCANI", "VIA COLLINA 4"),
			new Nome("CAIRO", "CIRILLI", "VIA MAZZINI 173"),
			new Nome("CAL", "SCARAFIOCCA", "VIA FORANA"),
			new Nome("CALEB", "CODONI", "VIA FALERIENSE 4746"),
			new Nome("CALVIN", "VESPRINI", "VIA VALLESCURA"),
			new Nome("CAMDEN", "BELLETTI", "VIA MAR IONIO 24"),
			new Nome("CAMRON", "ASFALTO", "VIA LUNGO TENNA 556"),
			new Nome("CANUTE", "MECONI", "VIA F.CORRIDONI 78"),
			new Nome("DACRE", "BENEDETTI", "VIA OBERDAN 37"),
			new Nome("DALEY", "BIANCUCCI", "VIA MARSALE 3"),
			new Nome("DALLAS", "BIANCUCCI", "VIA MALACARIA 1"),
			new Nome("DALTON", "BIOCCHI", "VIA C. PAVESE 1/3"),
			new Nome("DALY", "BIONDI", "VIA FALERIENSE EST 1"),
			new Nome("DAMIAN", "BIONDI", "VIA DELLA COSTITUZIONE ,88"),
			new Nome("DAMION", "BENEDETTI", "VIA OGNISSANTI 28"),
			new Nome("DAMON", "BIONDI", "S. CATERINA 2420"),
			new Nome("DANE", "BERDINI", "M.GIOIA ,75"),
			new Nome("DANNIE", "BIONDI", "VIA CAMPANIA 1"),
			new Nome("EARL", "CARBONI", "VIA DELLE VIGNE DI MORENA"),
			new Nome("EARLE", "CARDARELLI", "VIA NIBBI"),
			new Nome("EARNEST", "CARDARELLI", "VIA CERRETINO"),
			new Nome("EBENEZER", "CARDINALI", "STRADA SAN FILIPPO 17/A"),
			new Nome("ED", "FABIANI", "VIA MAIELLA 1"),
			new Nome("EDDY", "BELKADI", "REGINA MARGHERITA 12"),
			new Nome("EDGAR", "PETRITOLI", "VIA PONTENUOVO 9"),
			new Nome("EDISON", "CARLOME'", "VIA SAN GIORGIO 20"),
			new Nome("EDMUND", "SCALELLA", "VIA GABBIANO 4/A"),
			new Nome("EDRIC", "SCALELLA", "VIA GABBIANO 4/B"),
			new Nome("FABIAN", "SANTARELLI", "VIA CAMPIGLIONE 43"),
			new Nome("FARLEY", "PENNACCHIETTI", "VIA A. TOSCANINI 3"),
			new Nome("FARON", "MARCOZZI", "VIA ETT. FIERAMOSCA 3"),
			new Nome("FARRAN", "DEL GATTO", "VIA A. COSTA 474"),
			new Nome("FELIX", "CINTIO", "VIA APPENNINI 145"),
			new Nome("FENTON", "MARZIALI", "VIA NORCIA 8"),
			new Nome("FERDIE", "SCALPELLI", "VIA SALETTE 42"),
			new Nome("FERDINAND", "CATINI", "TACITO 2/A"),
			new Nome("FERDY", "COTINI", "VIA MAZZINI 52"),
			new Nome("FIDO", "CATINI", "VIA SOLFERINO 72"),
			new Nome("GABE", "FERRACUTI", "VIA XVIII SETTEMBRE 67"),
			new Nome("GABRIEL", "FIORINI", "VIA PORTA ROMANA N.58"),
			new Nome("GAGE", "SCARCIGLIA", "VIA PAPA GIOVANNI XXIII N.61"),
			new Nome("GALEN", "ZOPPO MARTELLINI", "VIA PONTE ROTTO 8"),
			new Nome("GALL", "MECOZZI", "VIA PIEMONTE 30"),
			new Nome("GARETH", "FORMENTINI", "VIA I. CALVINO 36"),
			new Nome("GAREY", "CIFANI", "VIA CAGLIARI 53"),
			new Nome("GARFIELD", "FRIFRINI", "VIA LOMBARDIA 155"),
			new Nome("GARLAND", "GIOMMARINI", "VIA SALETTE 62/C"),
			new Nome("GARRET", "PARNOFIELLO", "VIA COLOMBO 142"),
			new Nome("HAL", "DE LEONARDIS", "VIA CASTELFIDARDO 65"),
			new Nome("HALE", "SILVERI", "VIA G. LEOPARDI 49"),
			new Nome("HALL", "DETTO", "CORSICA N 10"),
			new Nome("HALLAM", "MUZI", "VIA UMBERTO I"),
			new Nome("HAMILTON", "MAZZA", "VIA PALESTRO 69"),
			new Nome("HAMMOND", "IOMMI", "VIA MAZZINI 92"),
			new Nome("HANK", "MARANESI", "VIA FIRENZE 73"),
			new Nome("HARDING", "MARCONI", "VIA 5 GIORNATE"),
			new Nome("HARDY", "MARTELLINI", "VIA TASSO 48"),
			new Nome("HARLAN", "PASQUALI", "VIA GARIBALDI 15"),
			new Nome("IAN", "CORTUCCI", "VIA PISACANE 11"),
			new Nome("IKE", "MORICONI", "VIA A. DIAZ"),
			new Nome("INGRAM", "COGNIGNI", "VIA PALERMO 20"),
			new Nome("INIGO", "COGNIGNI", "VIA DELLA COSTITUZIONE 242"),
			new Nome("INNOCENT", "COGNIGNI", "VIA G. BRUNO 20"),
			new Nome("IRA", "COGNIGNI", "VIA DELLA COSTITUZIONE"),
			new Nome("IRVIN", "COGNIGNI", "VIA DEI SIBILLINI 66"),
			new Nome("IRVINE", "COGNIGNI", "VIA SALICI 11"),
			new Nome("IRVING", "DAINA", "VIA L.GELLI 2"),
			new Nome("ISAAC", "COGNIGNI", "VIA SANTA MARIA 504"),
			new Nome("LAKE", "DE VITA", "VIA ANCONA 21"),
			new Nome("LALO", "DEVOTELLI", "VIA COLLE TENNA"),
			new Nome("LAMBERT", "DEZI", "VIA L. MERCANTINI"),
			new Nome("LANCE", "DI BELLA", "VIA DELLA COSTITUZIONE 134"),
			new Nome("LANCELOT", "DI CESILE", "VIA COLLODI"),
			new Nome("LANDON", "DI CLEMENTI", "VIA POZZETTO 687"),
			new Nome("LANE", "DI COLA", "VIALE TRENTO NUNZI 60"),
			new Nome("LANFORD", "DI CROCE", "VIA CAPPUCCINI 21"),
			new Nome("LANNY", "TRAINI", "CONTRADA S.BIAGIO 8"),
			new Nome("LARKIN", "SANTONI", "VIA MEAZZA 6"),
			new Nome("MAGNUS", "MASSIMILIANI", "VIA ANGELI 513"),
			new Nome("MAITLAND", "FRATALOCCHI", "VIA ROMA 1/A"),
			new Nome("MAJOR", "MONALDI", "VIA COLLE 8"),
			new Nome("MALACHI", "FERRONI", "VIA PALESTRO 105"),
			new Nome("MALCOLM", "PAGLIARETTA", "VIA XXV APRILE 6"),
			new Nome("MANFRED", "SANTINI", "VIA ANCONA 138"),
			new Nome("MANLEY", "FERRAMONDO", "VIA MAZZINI 286"),
			new Nome("MANNY", "FERRETTI", "VIA FALERIENSE, 4607"),
			new Nome("MANSEL", "MORICONI", "VIA CAMERA, 40"),
			new Nome("MANUEL", "MARINOZZI", "VIA PORTI 2"),
			new Nome("NANDY", "GALLETTI", "VIA PORTA ROMANA 109"),
			new Nome("NAPIER", "GAMBINI", "VIA FONTANA 5"),
			new Nome("NAT", "GASPARI", "VIA DELLA REPUBBLICA 58"),
			new Nome("NATHAN", "MANCINI", "VIA VOLTURNO 11"),
			new Nome("NATHANIEL", "GASPARRINI", "VIA EINAUDI 104"),
			new Nome("NED", "GASPARRONI", "VIA POMPEIANA 218"),
			new Nome("NEELY", "PISTELLI", "ABRUZZI 10"),
			new Nome("NEIL", "GAUDENZI", "VIA TRINITA' 28"),
			new Nome("NELSON", "GAUDENZI", "VIA G.MATTEOTTI 75"),
			new Nome("NEVIL", "GENTILI", "VIA G.SPONTINI 16"),
			new Nome("OBERON", "GISMONDI", "VIA ELPIDIENSE NORD 27"),
			new Nome("ODELL", "GIULIETTI", "VIA ROMA 70"),
			new Nome("OGDEN", "GIULI", "VIA PERGOLESI 6"),
			new Nome("OLIVER", "GIULIANO", "VIA 24 MAGGIO 11"),
			new Nome("OMEGA", "GIULIETTI", "VIA SABINO,3"),
			new Nome("ORMEROD", "GIUSTINI", "VIA PORTA ROMANA 58"),
			new Nome("ORMOND", "MICHELINI", "VIA PANTANETTO 7/B"),
			new Nome("ORRELL", "MALLONI", "VIA S.SEVERINO 3"),
			new Nome("ORSON", "VESPRINI", "VIA TENNA 7"),
			new Nome("ORVAL", "SILENZI", "VIA A. EINSTEIN 5"),
			new Nome("PACE", "ROMANELLI", "VIA UNGARETTI 88"),
			new Nome("PADEN", "OFFIDANI", "VIA ROMAGNA"),
			new Nome("PAISE", "MECOZZI", "TENNA 47"),
			new Nome("PALMER", "PETRUCCI", "VIA VECCHIA PORTO 1907"),
			new Nome("PANCRAS", "GRAZIOLI", "VIA SUSANNA"),
			new Nome("PARRIS", "GRIFI", "VIA MONTE MARINO,1"),
			new Nome("PATRICK", "GRYGIERCZYZ", "VIA UMBERTO IÝ"),
			new Nome("PATTON", "GRILLI", "VIA EMILIA,54"),
			new Nome("PAUL", "GROTTESI", "VIA LAZIO,13"),
			new Nome("PEARCE", "GUIDARELLI", "VIA G.SPONTINI 16"),
			new Nome("QUANAH", "MOZZORECCHIA", "VIA ELPIDIENSE 74"),
			new Nome("QUANAH", "SIMONETTI", "VIA N. SAURO 74"),
			new Nome("QUENTIN", "DINATO", "VIA COTECHININ.48"),
			new Nome("QUENTIN", "PICCININI", "VIA STORNO 5"),
			new Nome("QUIN", "COLANTONI", "VIA G. BRODOLINI 15"),
			new Nome("QUIN", "IAGATTI", "VIA TIEPOLO 1"),
			new Nome("QUINCEY", "IGNAZI", "VIA NAZIONALE 61"),
			new Nome("QUINCY", "ILARI", "VIA S.CARLO 33"),
			new Nome("QUINTIN", "ILARI", "VIA S. STEFANO N.4"),
			new Nome("QUINTON", "ILARI", "VIA MAZZINI"),
			new Nome("RADCLIFF", "ILARI", "C.DA LANQUA 3"),
			new Nome("RAEBURN", "IOBBI", "B.GO ROSSELLI 166"),
			new Nome("RAFE", "IOMMI", "VIA SOLFERINO"),
			new Nome("RAINARD", "IOMMI", "VIA STAZIONE"),
			new Nome("RALEIGH", "ISIDORI", "VIA VOLPI 12"),
			new Nome("RALF", "ISIDORI", "VIALE ROMA 21"),
			new Nome("RALPH", "MARINAI", "VIA BERGAMASCA 7"),
			new Nome("RALPHIE", "CINTI", "VIALE EUROPA"),
			new Nome("RAMSEY", "MARZIALI", "VIA DIOTALLEVI 2"),
			new Nome("RANDAL", "PETTINARI", "VIA SPONTINI"),
			new Nome("SACHEVERELL", "PISTOLESI", "VIA SIMONI 8"),
			new Nome("SACHIE", "PAPETTI", "VIA CASTAGNA 30"),
			new Nome("SAMPSON", "PANICCIA'", "VIA RICOSTRUZIONE 7"),
			new Nome("SAMSON", "VALLASCIANI", "VIA SAN FILIPPO 21/B"),
			new Nome("SAMUEL", "PIETA'", "VIA S.GIOVANNI BOSCO 52"),
			new Nome("SANDFORD", "LUCIANI", "VIA S. MARTINO"),
			new Nome("SANFORD", "MENICALI", "C.DA PALESTRINA 46"),
			new Nome("SAWYER", "MALAVOLTA", "VIA TRIESTE 20"),
			new Nome("SAXON", "MARANGONI", "VIA VERROCCHIO 17"),
			new Nome("SSDDDDF", "MILOZZI", "VIA CISTERNA 5/A"),
			new Nome("TAD", "MAGLIANESI", "VIA FALERIENSE"),
			new Nome("TALBOT", "MAGLIANESI", "VIA PIANE MONTEVERDE,20"),
			new Nome("TARQUIN", "MAGRINI", "VIA XX SETTEMBRE N.48"),
			new Nome("TATTON", "BRACONI", "VIA C. CATTANEO"),
			new Nome("TED", "MANCINI", "VIA CILEA 10"),
			new Nome("TEDDY", "MANCINI", "VIA E.FERMI, 17"),
			new Nome("TEL", "MANCINI", "VIA CALDARETTE ETE 4"),
			new Nome("TENNYSON", "MANCINI", "VIA DEL RIO ,6"),
			new Nome("TERANCE", "MANDOLESI", "VIALE TRENTO,18"),
			new Nome("TERENCE", "MANDOLESI", "VIA S. M. APPARENTE 62"),
			new Nome("ULAND", "MARZIALI", "VIA GUAZZETTI 236"),
			new Nome("ULAND", "SCARTOZZI", "VIA CALCINARI ,19"),
			new Nome("ULRIC", "CURI", "VIA COSTE,25"),
			new Nome("ULRIC", "MARZIALI", "VIA S.STEFANO,2"),
			new Nome("ULYSSES", "MARZIALI", "VIA TRONTO 21"),
			new Nome("ULYSSES", "PIATTONI", "VIA RIVA DEL PESCATORE"),
			new Nome("UPTON", "MARZIALI", "VIA BILLE' N14"),
			new Nome("UPTON", "PIATTONI", "VIA DORICA 2"),
			new Nome("URBAN", "LUCCI", "VIA ENRICO NEDI, 52"),
			new Nome("URBAN", "SALVATORI", "VIA PASCOLLA 9/4"),
			new Nome("VALENTINE", "MARZIALI", "VIA PIAVE 15"),
			new Nome("VANCE", "RIPA", "VIA BELGIO 16"),
			new Nome("VAUGHAN", "VITA", "VIA ROSSINI 3"),
			new Nome("VAUGHN", "COSTANZI", "VIA GIORGIONE 7"),
			new Nome("VERE", "MATTII", "VIA KENNEDY 1"),
			new Nome("VERGIL", "VECCHI", "VIA CROCEDIVIA 4"),
			new Nome("VERNON", "ALEANDRI", "VIA G. SPONTINI"),
			new Nome("VICTOR", "TULLI", "VIA S. LUCIA 34"),
			new Nome("VIN", "RIBICHINI", "VIA ANGELELLI 3"),
			new Nome("VINAL", "CIARROCCHI", "VIA S. CROCE 3847"),
			new Nome("ZACH", "NUNZI", "VIA A.COSTA"),
			new Nome("ZACHARIAH", "NUNZI", "VIA TRE CAMINI 1"),
			new Nome("ZACHARIAS", "RACCICHINI", "BORGO TRENTO 7"),
			new Nome("ZACHARY", "MECONI", "VIA A.VOLTA, 11"),
			new Nome("ZACHERY", "MECOZZI", "VIA N.SAURO,15"),
			new Nome("ZACK", "MECOZZI", "C.SO BACCIO N.47"),
			new Nome("ZACKARY", "MECOZZI", "VIA R.LOMBARDI,42"),
			new Nome("ZACKERY", "MECOZZI", "VIA PIAVE 3"),
			new Nome("ZAK", "MECOZZI", "VIA SCHIAFFINO,116"),
			new Nome("ZANDER", "MECOZZI", "VIA S.MARCO")
	};
	
	private HashSet<Integer> used = new HashSet<Integer>();
	
	/**
	 * 
	 * @return
	 */
	public Nome getNameNotUsed() {
		return people[getPosNotUsed()];
	}
	
	public Nome getName() {
		return people[Utility.randInt(0, people.length-1)];
	}
	
	private int getPosNotUsed() {
		int pos = 0;
		
		 do { 
			 pos = Utility.randInt(0, people.length-1);
		 } while(used.contains(pos));
		 
		 used.add(pos);
		return pos;
	}
	
	


}
